[package]
name = "cosmic-bg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
sctk = { package = "smithay-client-toolkit", git = "https://github.com/Smithay/client-toolkit", rev = "a3d1af8" }
cosmic-bg-config = { path = "./cosmic-bg-config" }
anyhow = "1.0"
notify = "5.0"
dirs = "4.0"
walkdir = "2.3"
itertools = "0.10"
rand = "0.8"
cosmic-config = { path = "../cosmic-config" }
ron = "0.8"
[workspace]
members = [
    "cosmic-bg-config"
]
